sudo: false
language: node_js

node_js:
  - node

script:
  - npm run lint
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  - email: false
